BUG: Fix runtime error related to missing mainWindow()
This commit fixes a regression most likely introduced by r24155 (ENH: Fixes
#3549. Import scripted module as python module)

Error fixed by this commit is the following:

//--------
Traceback (most recent call last):
  File "/home/jcfr/.config/NA-MIC/Extensions-24305/PET-IndiC/lib/Slicer-4.4/qt-scripted-modules/PETIndiC.py", line 338, in labelModified
    pd = qt.QProgressDialog('Calculating...', 'Cancel', 0, 100, mainWindow())
NameError: global name 'mainWindow' is not defined
//--------